on:
  workflow_dispatch:
    branches: [master]
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  goreadme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update README.md from Go docs
        uses: posener/goreadme@v1.4.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

